cipher:
	gcc -Wall -Wextra -Werror cipher.c logger.c -o ../build/cipher
logging_cipher:
	gcc -Wall -Wextra -Werror cipher.c logger.c -o ../build/cipher
linter:
	python3 ../materials/linters/cpplint.py --extensions=c *