CC=gcc
FLAG=-Wall -Wextra -Werror

all: door_struct list_test
	
clean:
	rm ../build/Q*

door_struct:
	gcc -Wall -Wextra -Werror door_struct.c dmanager_module.c -o ../build/Quest_1
list_test:
	gcc -Wall -Wextra -Werror list_test.c list.c -o ../build/Quest_2
rebuild:
	